services:  
  digikala-bot:
    build: app
    restart: unless-stopped
    command: python3 app.py
    env_file:
      - .env
    volumes:
      - ./app:/app
    networks:
      - data
      - mongo-net
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN}`)"
      # - "traefik.http.routers.${PROJECT_NAME}.middlewares=https-redirect"
      - "traefik.http.routers.${PROJECT_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik-net"

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis.data:/data
    networks:
      - data

networks:
  data:
  mongo-net:
    external: true
  traefik-net:
    external: true